// Generates a standalone bash script from a laio Session configuration.
// The script recreates the tmux session without requiring the laio binary.

use crate::common::config::{FlexDirection, Pane, Script, Session, Window};
use crate::common::path::sanitize_path;

use super::mux::first_pane_path;
use super::Dimensions;

pub(crate) const DEFAULT_WIDTH: usize = 200;
pub(crate) const DEFAULT_HEIGHT: usize = 50;

/// Static bash function that reproduces `TmuxClient::layout_checksum` (a CRC-16
/// variant) so generated scripts can checksum their own layout strings.
const CHECKSUM_FUNCTION: &str = r#"# Compute tmux layout checksum (CRC-16 variant)
layout_checksum() {
    local layout="$1"
    local csum=0
    for (( i=0; i<${#layout}; i++ )); do
        local byte
        byte=$(printf '%d' "'${layout:$i:1}")
        csum=$(( ((csum >> 1) | ((csum & 1) << 15)) + byte ))
        csum=$(( csum & 0xFFFF ))
    done
    printf '%04x' "$csum"
}"#;

/// Static guard that re-attaches to an already-running session instead of
/// recreating it.
const SESSION_GUARD: &str = r#"# Attach to existing session if it already exists
if tmux has-session -t "$SESSION" 2>/dev/null; then
    tmux attach-session -t "$SESSION"
    exit 0
fi"#;

/// Result of walking a pane subtree: the tmux layout string plus the bash lines
/// that create the panes and configure them afterwards. Returned by value so no
/// caller has to thread a mutable accumulator.
struct PaneOutput {
    layout: String,
    create_lines: Vec<String>,
    post_lines: Vec<String>,
    next_counter: usize,
}

pub(crate) fn generate_script(session: &Session, dimensions: &Dimensions) -> String {
    let windows: Vec<String> = session
        .windows
        .iter()
        .enumerate()
        .flat_map(|(i, window)| window_lines(session, window, i, dimensions))
        .collect();

    let delay = match session.pane_cmd_delay {
        Some(delay_ms) => vec![format!("sleep {}", delay_ms as f64 / 1000.0), String::new()],
        None => Vec::new(),
    };

    [
        header(session),
        checksum_function(),
        session_guard(),
        startup(session),
        create_session(session),
        shutdown_hook(session),
        windows,
        delay,
        attach(),
        vec![String::new()],
    ]
    .concat()
    .join("\n")
}

fn header(session: &Session) -> Vec<String> {
    vec![
        "#!/usr/bin/env bash".to_string(),
        "# Generated by laio - https://laio.sh".to_string(),
        format!("# Session: {}", session.name),
        "set -euo pipefail".to_string(),
        String::new(),
        format!("SESSION={}", shell_quote(&session.name)),
        String::new(),
    ]
}

fn checksum_function() -> Vec<String> {
    vec![CHECKSUM_FUNCTION.to_string(), String::new()]
}

fn session_guard() -> Vec<String> {
    vec![SESSION_GUARD.to_string(), String::new()]
}

fn startup(session: &Session) -> Vec<String> {
    if session.startup.is_empty() && session.startup_script.is_none() {
        return Vec::new();
    }

    let mut lines = vec![
        "# Startup commands".to_string(),
        "(".to_string(),
        format!("    cd {} || exit 1", shell_quote(&session.path)),
    ];

    lines.extend(session.startup.iter().map(|cmd| format!("    {cmd}")));

    if let Some(script) = &session.startup_script {
        lines.push("    bash <<'LAIO_STARTUP_SCRIPT'".to_string());
        lines.extend(script.to_string().lines().map(|line| format!("    {line}")));
        lines.push("LAIO_STARTUP_SCRIPT".to_string());
    }

    lines.push(")".to_string());
    lines.push(String::new());
    lines
}

fn create_session(session: &Session) -> Vec<String> {
    let first_pane = session
        .windows
        .first()
        .map(|window| first_pane_path(window, &window.effective_path(&session.path)))
        .unwrap_or_else(|| session.path.clone());

    let mut cmd = format!(
        "tmux new-session -d -s \"$SESSION\" -c {}",
        shell_quote(&first_pane)
    );
    for (key, value) in &session.env {
        cmd.push_str(&format!(" -e {}={}", shell_quote(key), shell_quote(value)));
    }

    let mut lines = vec!["# Create session".to_string(), cmd];

    if let Some(shell_path) = &session.shell {
        lines.push(format!(
            "tmux set-option -t \"$SESSION\" default-shell {}",
            shell_quote(shell_path)
        ));
    }

    lines.push(String::new());
    lines
}

fn shutdown_hook(session: &Session) -> Vec<String> {
    if session.shutdown.is_empty() && session.shutdown_script.is_none() {
        return Vec::new();
    }

    let mut lines = vec![
        "# Shutdown hook".to_string(),
        "_SHUTDOWN_SCRIPT=$(mktemp /tmp/laio-shutdown-XXXXXX)".to_string(),
        "chmod +x \"$_SHUTDOWN_SCRIPT\"".to_string(),
        "cat > \"$_SHUTDOWN_SCRIPT\" <<'LAIO_SHUTDOWN'".to_string(),
        "#!/usr/bin/env bash".to_string(),
        format!("cd {} || exit 1", shell_quote(&session.path)),
    ];

    lines.extend(session.shutdown.iter().map(|cmd| cmd.to_string()));

    if let Some(script) = &session.shutdown_script {
        lines.extend(script.to_string().lines().map(String::from));
    }

    lines.push("LAIO_SHUTDOWN".to_string());
    lines.push(
        "tmux set-hook -t \"$SESSION\" session-closed \"run-shell '$_SHUTDOWN_SCRIPT'\"".to_string(),
    );
    lines.push(String::new());
    lines
}

fn window_lines(session: &Session, window: &Window, window_index: usize, dimensions: &Dimensions) -> Vec<String> {
    let win_var = format!("WIN_{window_index}");
    let window_path = window.effective_path(&session.path);

    let mut lines = vec![format!("# -- Window: {} --", window.name)];

    if window_index == 0 {
        lines.push(format!(
            "{win_var}=$(tmux display-message -t \"$SESSION\" -p \"#I\")"
        ));
        lines.push(format!(
            "tmux rename-window -t \"$SESSION:${win_var}\" {}",
            shell_quote(&window.name)
        ));
    } else {
        let path = first_pane_path(window, &window_path);
        lines.push(format!(
            "{win_var}=$(tmux new-window -Pd -t \"$SESSION\" -n {} -c {} -F \"#{{window_id}}\")",
            shell_quote(&window.name),
            shell_quote(&path),
        ));
    }

    if window.panes.is_empty() {
        lines.push(String::new());
        return lines;
    }

    let walk = walk_panes(
        &window.panes,
        &window.flex_direction,
        dimensions.width,
        dimensions.height,
        0,
        0,
        0,
        &window_path,
        &win_var,
        None,
        0,
    );

    lines.push(String::new());
    lines.push("# Create panes".to_string());
    lines.extend(walk.create_lines);

    if !walk.layout.is_empty() {
        lines.push(String::new());
        lines.push("# Apply layout".to_string());
        lines.push(format!("LAYOUT=\"{}\"", walk.layout));
        lines.push("CSUM=$(layout_checksum \"$LAYOUT\")".to_string());
        lines.push(format!(
            "tmux select-layout -t \"$SESSION:${win_var}\" \"$CSUM,$LAYOUT\""
        ));
    }

    if !walk.post_lines.is_empty() {
        lines.push(String::new());
        lines.extend(walk.post_lines);
    }

    lines.push(String::new());
    lines
}

fn walk_panes(
    panes: &[Pane],
    direction: &FlexDirection,
    width: usize,
    height: usize,
    start_x: usize,
    start_y: usize,
    depth: usize,
    window_path: &str,
    win_var: &str,
    inherited_pane_var: Option<&str>,
    counter: usize,
) -> PaneOutput {
    let flex_total: usize = panes.iter().map(|p| p.flex).sum();
    let (mut current_x, mut current_y) = (start_x, start_y);
    let mut pane_strings: Vec<String> = Vec::new();
    let mut create_lines: Vec<String> = Vec::new();
    let mut post_lines: Vec<String> = Vec::new();
    let mut counter = counter;
    let mut num_dividers: usize = 0;

    for (index, pane) in panes.iter().enumerate() {
        let (pane_width, pane_height, next_x, next_y) = match calculate_pane_dimensions(
            direction, width, height, current_x, current_y, depth, num_dividers, pane.flex,
            flex_total, index, panes.len(),
        ) {
            Some(v) => v,
            None => continue,
        };

        if depth > 0 || index > 0 {
            num_dividers += 1;
        }

        let pane_var = if index > 0 {
            let var = format!("PANE_{counter}");
            counter += 1;
            let path = sanitize_path(
                pane.first_leaf_path().unwrap_or(&".".to_string()),
                &window_path.to_string(),
            );
            create_lines.push(format!(
                "{var}=$(tmux split-window -t \"$SESSION:${win_var}\" -c {} -P -F \"#{{pane_id}}\")",
                shell_quote(&path),
            ));
            create_lines.push(format!("tmux select-layout -t \"$SESSION:${win_var}\" tiled"));
            var
        } else if depth == 0 {
            let var = format!("PANE_{counter}");
            counter += 1;
            create_lines.push(format!(
                "{var}=$(tmux display-message -t \"$SESSION:${win_var}\" -p \"#{{pane_id}}\")"
            ));
            create_lines.push(format!("tmux select-layout -t \"$SESSION:${win_var}\" tiled"));
            var
        } else {
            inherited_pane_var.unwrap().to_string()
        };

        if let Some(name) = &pane.name {
            post_lines.push(format!(
                "tmux select-pane -t \"${pane_var}\" -T {}",
                shell_quote(name)
            ));
        }

        if let Some(style) = &pane.style {
            post_lines.push(format!(
                "tmux select-pane -t \"${pane_var}\" -P {}",
                shell_quote(style)
            ));
        }

        let pane_layout = if !pane.panes.is_empty() {
            let child = walk_panes(
                &pane.panes,
                &pane.flex_direction,
                pane_width,
                pane_height,
                current_x,
                current_y,
                depth + 1,
                window_path,
                win_var,
                Some(&pane_var),
                counter,
            );
            create_lines.extend(child.create_lines);
            post_lines.extend(child.post_lines);
            counter = child.next_counter;
            child.layout
        } else {
            format!("{pane_width}x{pane_height},{current_x},{current_y},${{{pane_var}#%}}")
        };

        pane_strings.push(pane_layout);
        (current_x, current_y) = (next_x, next_y);

        if let Some(script) = &pane.script {
            post_lines.extend(pane_script_lines(&pane_var, script));
        }

        let cmds: Vec<String> = pane.commands.iter().map(|c| c.to_string()).collect();
        if !cmds.is_empty() {
            let mut send_keys = format!("tmux send-keys -t \"${pane_var}\"");
            for cmd_str in &cmds {
                send_keys.push_str(&format!(" {} C-m", shell_quote(cmd_str)));
            }
            post_lines.push(send_keys);
        }

        if pane.zoom {
            post_lines.push(format!("tmux resize-pane -Z -t \"${pane_var}\""));
        }

        if pane.focus {
            post_lines.push(format!("tmux select-pane -t \"${pane_var}\""));
        }
    }

    let layout = if pane_strings.len() > 1 {
        let (open, close) = match direction {
            FlexDirection::Column => ('[', ']'),
            FlexDirection::Row => ('{', '}'),
        };
        format!(
            "{width}x{height},{start_x},{start_y}{open}{}{close}",
            pane_strings.join(",")
        )
    } else if pane_strings.len() == 1 {
        pane_strings.into_iter().next().unwrap()
    } else {
        format!("{width}x{height},{start_x},{start_y}")
    };

    PaneOutput {
        layout,
        create_lines,
        post_lines,
        next_counter: counter,
    }
}

fn pane_script_lines(pane_var: &str, script: &Script) -> Vec<String> {
    let var = format!("_PANE_SCRIPT_{}", pane_var.replace("PANE_", ""));
    let mut lines = vec![
        format!("{var}=$(mktemp /tmp/laio-export-XXXXXX)"),
        format!("chmod +x \"${var}\""),
        format!("cat > \"${var}\" <<'LAIO_PANE_SCRIPT'"),
    ];
    lines.extend(script.to_string().lines().map(String::from));
    lines.push("LAIO_PANE_SCRIPT".to_string());
    lines.push(format!("tmux send-keys -t \"${pane_var}\" \"${var}\" C-m"));
    lines
}

fn attach() -> Vec<String> {
    vec![
        "# Attach to session".to_string(),
        "tmux attach-session -t \"$SESSION\"".to_string(),
    ]
}

fn calculate_pane_dimensions(
    direction: &FlexDirection,
    width: usize,
    height: usize,
    current_x: usize,
    current_y: usize,
    depth: usize,
    dividers: usize,
    flex: usize,
    flex_total: usize,
    index: usize,
    pane_count: usize,
) -> Option<(usize, usize, usize, usize)> {
    let is_last = index == pane_count - 1;

    match direction {
        FlexDirection::Column => {
            let h = calculate_dimension(depth, index, flex, flex_total, dividers, is_last, current_y, height)?;
            Some((width, h, current_x, current_y + h + 1))
        }
        FlexDirection::Row => {
            let w = calculate_dimension(depth, index, flex, flex_total, dividers, is_last, current_x, width)?;
            Some((w, height, current_x + w + 1, current_y))
        }
    }
}

fn calculate_dimension(
    depth: usize,
    index: usize,
    flex: usize,
    flex_total: usize,
    dividers: usize,
    is_last: bool,
    current_value: usize,
    total_value: usize,
) -> Option<usize> {
    if is_last {
        if current_value >= total_value {
            return None;
        }
        Some(total_value - current_value)
    } else if depth > 0 || index > 0 {
        Some(total_value * flex / flex_total - dividers)
    } else {
        Some(total_value * flex / flex_total)
    }
}

fn shell_quote(s: &str) -> String {
    if s.contains('\'') || s.contains('"') || s.contains(' ') || s.contains('$')
        || s.contains('\\') || s.contains('!') || s.contains('`') || s.contains('(')
        || s.contains(')') || s.contains('{') || s.contains('}') || s.contains('&')
        || s.contains(';') || s.contains('|') || s.contains('<') || s.contains('>')
        || s.contains('*') || s.contains('?') || s.contains('#') || s.contains('~')
    {
        format!("'{}'", s.replace('\'', "'\\''"))
    } else {
        format!("\"{s}\"")
    }
}
