// Generates a standalone bash script from a laio Session configuration.
// The script recreates the tmux session without requiring the laio binary.

use crate::common::config::{FlexDirection, Pane, Session, Window};
use crate::common::path::sanitize_path;

use super::mux::first_pane_path;
use super::Dimensions;

pub(crate) const DEFAULT_WIDTH: usize = 200;
pub(crate) const DEFAULT_HEIGHT: usize = 50;

struct ExportState {
    pane_counter: usize,
    create_lines: Vec<String>,
    post_lines: Vec<String>,
}

pub(crate) fn generate_script(session: &Session, dimensions: &Dimensions) -> String {
    let mut lines = Vec::new();

    emit_header(&mut lines, session);
    emit_checksum_function(&mut lines);
    emit_session_guard(&mut lines);
    emit_startup(&mut lines, session);
    emit_create_session(&mut lines, session);
    emit_shutdown_hook(&mut lines, session);

    for (i, window) in session.windows.iter().enumerate() {
        emit_window(&mut lines, session, window, i, dimensions);
    }

    if let Some(delay_ms) = session.pane_cmd_delay {
        let secs = delay_ms as f64 / 1000.0;
        lines.push(format!("sleep {secs}"));
        lines.push(String::new());
    }

    emit_attach(&mut lines);

    lines.push(String::new());
    lines.join("\n")
}

fn emit_header(lines: &mut Vec<String>, session: &Session) {
    lines.push("#!/usr/bin/env bash".to_string());
    lines.push(format!(
        "# Generated by laio - https://laio.sh"
    ));
    lines.push(format!("# Session: {}", session.name));
    lines.push("set -euo pipefail".to_string());
    lines.push(String::new());
    lines.push(format!("SESSION={}", shell_quote(&session.name)));
    lines.push(String::new());
}

fn emit_checksum_function(lines: &mut Vec<String>) {
    lines.push("# Compute tmux layout checksum (CRC-16 variant)".to_string());
    lines.push("layout_checksum() {".to_string());
    lines.push("    local layout=\"$1\"".to_string());
    lines.push("    local csum=0".to_string());
    lines.push("    for (( i=0; i<${#layout}; i++ )); do".to_string());
    lines.push("        local byte".to_string());
    lines.push("        byte=$(printf '%d' \"'${layout:$i:1}\")".to_string());
    lines.push(
        "        csum=$(( ((csum >> 1) | ((csum & 1) << 15)) + byte ))".to_string(),
    );
    lines.push("        csum=$(( csum & 0xFFFF ))".to_string());
    lines.push("    done".to_string());
    lines.push("    printf '%04x' \"$csum\"".to_string());
    lines.push("}".to_string());
    lines.push(String::new());
}

fn emit_session_guard(lines: &mut Vec<String>) {
    lines.push("# Attach to existing session if it already exists".to_string());
    lines.push(
        "if tmux has-session -t \"$SESSION\" 2>/dev/null; then".to_string(),
    );
    lines.push("    tmux attach-session -t \"$SESSION\"".to_string());
    lines.push("    exit 0".to_string());
    lines.push("fi".to_string());
    lines.push(String::new());
}

fn emit_startup(lines: &mut Vec<String>, session: &Session) {
    let has_startup = !session.startup.is_empty() || session.startup_script.is_some();
    if !has_startup {
        return;
    }

    lines.push("# Startup commands".to_string());
    lines.push("(".to_string());
    lines.push(format!("    cd {} || exit 1", shell_quote(&session.path)));

    for cmd in &session.startup {
        lines.push(format!("    {cmd}"));
    }

    if let Some(script) = &session.startup_script {
        lines.push("    bash <<'LAIO_STARTUP_SCRIPT'".to_string());
        for line in script.to_string().lines() {
            lines.push(format!("    {line}"));
        }
        lines.push("LAIO_STARTUP_SCRIPT".to_string());
    }

    lines.push(")".to_string());
    lines.push(String::new());
}

fn emit_create_session(lines: &mut Vec<String>, session: &Session) {
    lines.push("# Create session".to_string());

    let first_pane_path = session
        .windows
        .first()
        .map(|window| {
            let window_path = window.effective_path(&session.path);
            first_pane_path(window, &window_path)
        })
        .unwrap_or_else(|| session.path.clone());

    let mut cmd = format!(
        "tmux new-session -d -s \"$SESSION\" -c {}",
        shell_quote(&first_pane_path)
    );

    for (key, value) in &session.env {
        cmd.push_str(&format!(" -e {}={}", shell_quote(key), shell_quote(value)));
    }
    lines.push(cmd);

    if let Some(shell_path) = &session.shell {
        lines.push(format!(
            "tmux set-option -t \"$SESSION\" default-shell {}",
            shell_quote(shell_path)
        ));
    }

    lines.push(String::new());
}

fn emit_shutdown_hook(lines: &mut Vec<String>, session: &Session) {
    let has_shutdown = !session.shutdown.is_empty() || session.shutdown_script.is_some();
    if !has_shutdown {
        return;
    }

    lines.push("# Shutdown hook".to_string());
    lines.push("_SHUTDOWN_SCRIPT=$(mktemp /tmp/laio-shutdown-XXXXXX)".to_string());
    lines.push("chmod +x \"$_SHUTDOWN_SCRIPT\"".to_string());
    lines.push("cat > \"$_SHUTDOWN_SCRIPT\" <<'LAIO_SHUTDOWN'".to_string());
    lines.push("#!/usr/bin/env bash".to_string());
    lines.push(format!("cd {} || exit 1", shell_quote(&session.path)));

    for cmd in &session.shutdown {
        lines.push(cmd.to_string());
    }

    if let Some(script) = &session.shutdown_script {
        for line in script.to_string().lines() {
            lines.push(line.to_string());
        }
    }

    lines.push("LAIO_SHUTDOWN".to_string());
    lines.push(
        "tmux set-hook -t \"$SESSION\" session-closed \"run-shell '$_SHUTDOWN_SCRIPT'\"".to_string(),
    );
    lines.push(String::new());
}

fn emit_window(
    lines: &mut Vec<String>,
    session: &Session,
    window: &Window,
    window_index: usize,
    dimensions: &Dimensions,
) {
    let win_var = format!("WIN_{window_index}");
    let window_path = window.effective_path(&session.path);

    lines.push(format!("# -- Window: {} --", window.name));

    if window_index == 0 {
        lines.push(format!(
            "{win_var}=$(tmux display-message -t \"$SESSION\" -p \"#I\")"
        ));
        lines.push(format!(
            "tmux rename-window -t \"$SESSION:${win_var}\" {}",
            shell_quote(&window.name)
        ));
    } else {
        let path = first_pane_path(window, &window_path);
        lines.push(format!(
            "{win_var}=$(tmux new-window -Pd -t \"$SESSION\" -n {} -c {} -F \"#{{window_id}}\")",
            shell_quote(&window.name),
            shell_quote(&path),
        ));
    }

    if window.panes.is_empty() {
        lines.push(String::new());
        return;
    }

    let mut state = ExportState {
        pane_counter: 0,
        create_lines: Vec::new(),
        post_lines: Vec::new(),
    };

    let layout = walk_panes(
        &window.panes,
        &window.flex_direction,
        dimensions.width,
        dimensions.height,
        0,
        0,
        0,
        &window_path,
        &win_var,
        None,
        &mut state,
    );

    lines.push(String::new());
    lines.push("# Create panes".to_string());
    lines.extend(state.create_lines);

    if !layout.is_empty() {
        lines.push(String::new());
        lines.push("# Apply layout".to_string());
        lines.push(format!("LAYOUT=\"{layout}\""));
        lines.push("CSUM=$(layout_checksum \"$LAYOUT\")".to_string());
        lines.push(format!(
            "tmux select-layout -t \"$SESSION:${win_var}\" \"$CSUM,$LAYOUT\""
        ));
    }

    if !state.post_lines.is_empty() {
        lines.push(String::new());
        lines.extend(state.post_lines);
    }

    lines.push(String::new());
}

fn walk_panes(
    panes: &[Pane],
    direction: &FlexDirection,
    width: usize,
    height: usize,
    start_x: usize,
    start_y: usize,
    depth: usize,
    window_path: &str,
    win_var: &str,
    inherited_pane_var: Option<&str>,
    state: &mut ExportState,
) -> String {
    let flex_total: usize = panes.iter().map(|p| p.flex).sum();
    let (mut current_x, mut current_y) = (start_x, start_y);
    let mut pane_strings: Vec<String> = Vec::new();
    let mut num_dividers: usize = 0;

    for (index, pane) in panes.iter().enumerate() {
        let (pane_width, pane_height, next_x, next_y) = match calculate_pane_dimensions(
            direction, width, height, current_x, current_y, depth, num_dividers, pane.flex,
            flex_total, index, panes.len(),
        ) {
            Some(v) => v,
            None => continue,
        };

        if depth > 0 || index > 0 {
            num_dividers += 1;
        }

        let pane_var = if index > 0 {
            let var = format!("PANE_{}", state.pane_counter);
            state.pane_counter += 1;
            let path = sanitize_path(
                pane.first_leaf_path().unwrap_or(&".".to_string()),
                &window_path.to_string(),
            );
            state.create_lines.push(format!(
                "{var}=$(tmux split-window -t \"$SESSION:${win_var}\" -c {} -P -F \"#{{pane_id}}\")",
                shell_quote(&path),
            ));
            state
                .create_lines
                .push(format!("tmux select-layout -t \"$SESSION:${win_var}\" tiled"));
            var
        } else if depth == 0 {
            let var = format!("PANE_{}", state.pane_counter);
            state.pane_counter += 1;
            state.create_lines.push(format!(
                "{var}=$(tmux display-message -t \"$SESSION:${win_var}\" -p \"#{{pane_id}}\")"
            ));
            state
                .create_lines
                .push(format!("tmux select-layout -t \"$SESSION:${win_var}\" tiled"));
            var
        } else {
            inherited_pane_var.unwrap().to_string()
        };

        if let Some(name) = &pane.name {
            state.post_lines.push(format!(
                "tmux select-pane -t \"${pane_var}\" -T {}",
                shell_quote(name)
            ));
        }

        if let Some(style) = &pane.style {
            state.post_lines.push(format!(
                "tmux select-pane -t \"${pane_var}\" -P {}",
                shell_quote(style)
            ));
        }

        let pane_layout = if !pane.panes.is_empty() {
            walk_panes(
                &pane.panes,
                &pane.flex_direction,
                pane_width,
                pane_height,
                current_x,
                current_y,
                depth + 1,
                window_path,
                win_var,
                Some(&pane_var),
                state,
            )
        } else {
            format!(
                "{pane_width}x{pane_height},{current_x},{current_y},${{{pane_var}#%}}"
            )
        };

        pane_strings.push(pane_layout);
        (current_x, current_y) = (next_x, next_y);

        let cmds: Vec<String> = pane.commands.iter().map(|c| c.to_string()).collect();
        if let Some(script) = &pane.script {
            emit_pane_script(state, &pane_var, script);
        }

        if !cmds.is_empty() {
            let mut send_keys = format!("tmux send-keys -t \"${pane_var}\"");
            for cmd_str in &cmds {
                send_keys.push_str(&format!(" {} C-m", shell_quote(cmd_str)));
            }
            state.post_lines.push(send_keys);
        }

        if pane.zoom {
            state.post_lines.push(format!(
                "tmux resize-pane -Z -t \"${pane_var}\""
            ));
        }

        if pane.focus {
            state.post_lines.push(format!(
                "tmux select-pane -t \"${pane_var}\""
            ));
        }
    }

    if pane_strings.len() > 1 {
        let (open, close) = match direction {
            FlexDirection::Column => ('[', ']'),
            FlexDirection::Row => ('{', '}'),
        };
        format!(
            "{width}x{height},{start_x},{start_y}{open}{}{close}",
            pane_strings.join(",")
        )
    } else if pane_strings.len() == 1 {
        pane_strings.into_iter().next().unwrap()
    } else {
        format!("{width}x{height},{start_x},{start_y}")
    }
}

fn emit_pane_script(state: &mut ExportState, pane_var: &str, script: &crate::common::config::Script) {
    let var = format!("_PANE_SCRIPT_{}", pane_var.replace("PANE_", ""));
    state.post_lines.push(format!(
        "{var}=$(mktemp /tmp/laio-export-XXXXXX)"
    ));
    state.post_lines.push(format!("chmod +x \"${var}\""));
    state
        .post_lines
        .push(format!("cat > \"${var}\" <<'LAIO_PANE_SCRIPT'"));
    for line in script.to_string().lines() {
        state.post_lines.push(line.to_string());
    }
    state.post_lines.push("LAIO_PANE_SCRIPT".to_string());
    state.post_lines.push(format!(
        "tmux send-keys -t \"${pane_var}\" \"${var}\" C-m"
    ));
}

fn emit_attach(lines: &mut Vec<String>) {
    lines.push("# Attach to session".to_string());
    lines.push("tmux attach-session -t \"$SESSION\"".to_string());
}

fn calculate_pane_dimensions(
    direction: &FlexDirection,
    width: usize,
    height: usize,
    current_x: usize,
    current_y: usize,
    depth: usize,
    dividers: usize,
    flex: usize,
    flex_total: usize,
    index: usize,
    pane_count: usize,
) -> Option<(usize, usize, usize, usize)> {
    let is_last = index == pane_count - 1;

    match direction {
        FlexDirection::Column => {
            let h = calculate_dimension(depth, index, flex, flex_total, dividers, is_last, current_y, height)?;
            Some((width, h, current_x, current_y + h + 1))
        }
        FlexDirection::Row => {
            let w = calculate_dimension(depth, index, flex, flex_total, dividers, is_last, current_x, width)?;
            Some((w, height, current_x + w + 1, current_y))
        }
    }
}

fn calculate_dimension(
    depth: usize,
    index: usize,
    flex: usize,
    flex_total: usize,
    dividers: usize,
    is_last: bool,
    current_value: usize,
    total_value: usize,
) -> Option<usize> {
    if is_last {
        if current_value >= total_value {
            return None;
        }
        Some(total_value - current_value)
    } else if depth > 0 || index > 0 {
        Some(total_value * flex / flex_total - dividers)
    } else {
        Some(total_value * flex / flex_total)
    }
}

fn shell_quote(s: &str) -> String {
    if s.contains('\'') || s.contains('"') || s.contains(' ') || s.contains('$')
        || s.contains('\\') || s.contains('!') || s.contains('`') || s.contains('(')
        || s.contains(')') || s.contains('{') || s.contains('}') || s.contains('&')
        || s.contains(';') || s.contains('|') || s.contains('<') || s.contains('>')
        || s.contains('*') || s.contains('?') || s.contains('#') || s.contains('~')
    {
        format!("'{}'", s.replace('\'', "'\\''"))
    } else {
        format!("\"{s}\"")
    }
}
