---
name: laio

path: .

env:
  foo: bar

windows:
  - name: code
    flex_direction: column
    panes:
      - commands:
          - command: $EDITOR

  - name: misc
    panes:
      - flex: 1
        panes:
          - commands:
              - command: git
                args:
                  - fetch
                  - --all
      - flex: 1
        flex_direction: column
        panes:
          - flex: 1
            path: docs
            commands:
              - command: zola
                args:
                  - serve
          - flex: 4
