---
name: laio-test

path: .

commands:
  - echo "start"
  - sleep 10
  - echo "done"
windows:
  - name: code
    panes:
      - commands:
          - $EDITOR

  - name: misc
    flex_direction: column
    panes:
      - flex: 1
        path: . # a relative path to root
        flex_direction: row
        panes:
          - flex: 1
            flex_direction: column
            panes:
              - flex: 1
                path: ./src
              - flex: 1
                path: src/laio
          - flex: 5
      - flex: 1
        path: . # a relative path to root
