---
name: laio

path: .

env:
  foo: bar

windows:
  - name: code
    flex_direction: column
    panes:
      - commands:
          - $EDITOR

  - name: misc
    panes:
      - flex: 1
        panes:
          - commands:
              - git fetch --all
      - flex: 1
        flex_direction: column
        panes:
          - flex: 1
            path: docs
            commands:
              - zola serve
          - flex: 4
