---
name: laio

path: .

env:
  foo: bar

windows:
  - name: code
    flex_direction: column
    panes:
      - flex: 5
        zoom: true
        commands:
          - $EDITOR
      - flex: 1

  - name: misc
    panes:
      - flex: 1
      - flex: 1
        flex_direction: column
        panes:
          - flex: 1
            path: docs
            commands:
              - zola serve
          - flex: 4
