---
name: laio

path: .

env:
  foo: bar

startup_script: |
  #!/usr/bin/env nu

  print "Hello from laio scripts!"

windows:
  - name: code
    flex_direction: column
    panes:
      - commands:
          - command: nvim

  - name: misc
    panes:
      - flex: 1
      - flex: 1
        flex_direction: column
        panes:
          - flex: 1
            path: docs
            commands:
              - command: zola
                args:
                  - serve
          - flex: 4
