---
name: rmux-test

path: .

windows:
  - name: code
    panes:
      - commands:
          - $EDITOR

  - name: misc
    flex_direction: column
    panes:
      - flex: 1
        path: . # a relative path to root
        flex_direction: row
        panes:
          - flex: 1
          - flex: 2
      - flex: 2
        path: . # a relative path to root
      - flex: 1
        path: . # a relative path to root
