---
name: rmux-dev

path: .

windows:
  - name: code
    layout: main-horizontal
    panes:
      - type: horizontal
        commands:
          - $EDITOR

  - name: misc
    layout: tiled 
    panes:
      - type: horizontal
        path: . # a relative path to root
      - type: horizontal
        path: . # a relative path to root
