# https://numtide.github.io/devshell
name = "laio devshell"

packages = [
]

[[commands]]
package = "zola"
category = "ssg"

[[commands]]
package = "act"
category = "github"
# [devshell.startup.rust]
# text = """
# # rustup default stable
# # rustup component add rust-src
# """
