# https://numtide.github.io/devshell
name = "rmx devshell"

packages = [
]

# [[commands]]
# package = "rustup"
# name = "rustup"
# category = "rust"

# [[commands]]
# package = "cargo-cross"
# name = "cross"
# category = "rust"

# [devshell.startup.rust]
# text = """
# # rustup default stable
# # rustup component add rust-src
# """
