---
name: Foo 

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-linux
          # - name: linux-arm64
          #   runner: ubuntu-latest
          #   target: aarch64-linux
          # - name: macos-amd64
          #   runner: macos-latest
          #   target: x86_64-darwin
          # - name: macos-arm64
          #   runner: macos-latest
          #   target: aarch64-darwin

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      # - run: nix flake check --impure
      - run: |
          nix build .#laio-${{ matrix.target }} -L
          file result/bin/laio
          nix-hash --type sha256 --flat --base32 result/bin/laio 

      # - id: release-notes
      #   run: |
      #     latest_tag=$(git describe --tags --abbrev=0)
      #     release_notes=$(git log ${latest_tag}..remotes/origin/main --oneline --format="%s" |
      #     sed 's/^[ \t]*//;s/[ \t]*$//' |
      #     grep -v '^$' |
      #     grep -v '^Co-authored' |
      #     sort | uniq)
      #     echo $release_notes > /tmp/release_notes.txt
      #
      # - name: test release notes
      #   run: |
      #     cat /tmp/release_notes.txt
