---
name: Foo 

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        include:
          # - name: linux-amd64
          #   runner: ubuntu-latest
          #   target: x86_64-linux
          - name: linux-arm64
            runner: ubuntu-latest
            target: aarch64-linux
          # - name: macos-amd64
          #   runner: macos-latest
          #   target: x86_64-apple-darwin
          # - name: macos-arm64
          #   runner: macos-latest
          #   target: aarch64-apple-darwin

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      # - run: nix flake check --impure
      - run: |
          . /root/.nix-profile/etc/profile.d/nix.sh
          nix build .#packages.${{ matrix.target }}.rmx --impure
