---
name: merge to main

on:
  push:
    paths:
      - src/**
      - .github/workflows/main.yaml
      - .github/workflows/release.yaml
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Test Binary
        run: |
          cargo test

      - name: Set up Git
        run: |
          git config --global user.name "Christian Kemper"
          git config --global user.email "christian.kemper@me.com"

      - name: Bump version in Cargo.toml
        run: |
          VERSION=$(grep '^version' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          NEW_VERSION=$(echo "${VERSION}" | awk -F. '{ printf("%d.%d.%d", $1, $2, $3 + 1) }')
          sed -i "s/^version = \".*\"/version = \"${NEW_VERSION}\"/" Cargo.toml
          git add Cargo.toml
          git commit -m "Bump version in Cargo.toml to ${NEW_VERSION}"
          git push

      - name: Update develop branch with version change
        run: |
          git checkout develop
          git merge main
          git push
