---
name: merge to main

on:
  workflow_run:
    workflows:
      - test
    types:
      - completed
  push:
    paths:
      - src/**
      - .github/workflows/**
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "Christian Kemper"
          git config --global user.email "christian.kemper@me.com"

      - name: Get Cargo Version
        id: get_version
        run: |
          # Get the current version from Cargo.toml
          current_version=$(grep '^version' Cargo.toml | head -1 | awk '{print $3}' | tr -d '"')
          echo "current-version=${current_version}" >> $GITHUB_OUTPUT

      - name: Get next version
        id: get_next_version
        uses: ck3mp3r/semver-version-action@main
        with:
          current-version: ${{ steps.get_version.outputs.current-version }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        if: ${{ steps.get_version.outputs.current-version }} != ${{ steps.get_next_version.outputs.semver }}
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Create tag and update Cargo.toml if required.
        run: |
          if [ "${{ steps.get_version.outputs.current-version }}" == "${{ steps.get_next_version.outputs.semver }}" ]; then
            echo "Major or minor version have changed. Tagging with version v${current_version}"
            git tag "v${{ steps.get_version.outputs.current-version }}"
            git push origin "v${{ steps.get_version.outputs.current-version }}"
          else
            new_version=${{ steps.get_next_version.outputs.semver }}
            echo "Tagging with new version: v${new_version}"
            sed -i "s/^version = \".*\"/version = \"${new_version}\"/" Cargo.toml
            cargo update -p rmx
            git add Cargo.toml Cargo.lock
            git commit -m "Bump version in Cargo.toml to ${new_version}"
            git push

            git tag "v${new_version}"
            git push origin "v${new_version}"
          fi
