---
name: merge to main

on:
  push:
    paths:
      - src/**
      - .github/workflows/main.yaml
    branches:
      - main

jobs:
  calver:
    runs-on: ubuntu-latest 
    outputs:
      calver-version: ${{ steps.calver.outputs.calver-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate CalVer version
        id: calver
        uses: ck3mp3r/calver-version-action@main
  bump:
    runs-on: ubuntu-latest
    needs: calver
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Test Binary
        run: |
          cargo test

      - name: Set up Git
        run: |
          git config --global user.name "Christian Kemper"
          git config --global user.email "christian.kemper@me.com"

      - name: Replace version in Cargo.toml
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ needs.calver.outputs.calver-version }}\"/" Cargo.toml
          git add Cargo.toml
          git commit -m "Update version in Cargo.toml to ${{ needs.calver.outputs.calver-version }}"
          git push
