---
name: Release

on:
  workflow_dispatch:

concurrency: 
  group: release
  cancel-in-progress: true

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Get Current Version
        id: get_current_version
        run: |
          # Get the current version from Cargo.toml
          current_version=$(grep '^version' Cargo.toml | head -1 | awk '{print $3}' | tr -d '"')
          echo "Current version is: ${current_version}"
          echo "current-version=${current_version}" >> $GITHUB_OUTPUT

      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: run preliminary checks and tests
        run: |
          nix flake check
          nix develop --command cargo test

      - name: Set up Git
        run: |
          git config --global user.name "Christian Kemper"
          git config --global user.email "christian.kemper@me.com"

      - name: Get next version
        id: get_next_version
        uses: ck3mp3r/semver-version-action@main
        with:
          current-version: ${{ steps.get_current_version.outputs.current-version }}

      - name: Create tag and update Cargo.toml if required.
        if: ${{ ! env.ACT }}
        run: |
          current_version=${{ steps.get_current_version.outputs.current-version }}
          if [ "${current_version}" == "${{ steps.get_next_version.outputs.semver }}" ]; then
            echo "Major or minor version have changed. Tagging with version v${current_version}"
            git tag "v${current_version}"
            git push origin "v${current_version}"
          else
            new_version=${{ steps.get_next_version.outputs.semver }}
            echo "Tagging with new version: v${new_version}"
            sed -i "s/^version = \".*\"/version = \"${new_version}\"/" Cargo.toml
            nix develop --command cargo update -p rmx
            git add Cargo.toml Cargo.lock
            git commit -m "Bump version in Cargo.toml to ${new_version}"
            git push

            git tag "v${new_version}"
            git push origin "v${new_version}"
          fi

  build:
    runs-on: ${{ matrix.os }}
    needs: 
      - bump
    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
        target: 
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        exclude:
          - os: macos-latest
            target: "x86_64-unknown-linux-musl"
          - os: macos-latest
            target: "aarch64-unknown-linux-musl"
          - os: ubuntu-latest
            target: "aarch64-apple-darwin"
          - os: ubuntu-latest
            target: "x86_64-apple-darwin"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Cargo Package Version
        run: echo "CARGO_PKG_VERSION=$(grep '^version' Cargo.toml | sed 's/version = "\(.*\)"/\1/')" >> $GITHUB_ENV

      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Binary
        run: nix build .#rmx

      - name: Upload Artifacts
        if: ${{ ! env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: rmx-${{ env.CARGO_PKG_VERSION }}-${{ matrix.target }}
          path: ${{ github.workspace }}/result/bin/rmx

  release:
    needs: 
      - build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # Log in to gh using the GitHub token
      - name: Log in to gh
        if: ${{ ! env.ACT }}
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Cargo Package Version
        if: ${{ ! env.ACT }}
        run: |
          echo "CARGO_PKG_VERSION=$(grep '^version' Cargo.toml | sed 's/version = "\(.*\)"/\1/')" >> $GITHUB_ENV

      # Create release
      - name: Create release
        if: ${{ ! env.ACT }}
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Prerelease v${{ env.CARGO_PKG_VERSION }}
          tag_name: v${{ env.CARGO_PKG_VERSION }}
          prerelease: true

  upload:
    needs: 
      - release
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl", "x86_64-apple-darwin", "aarch64-apple-darwin"]
    steps:
      # Log in to gh using the GitHub token
      - name: Log in to gh
        if: ${{ ! env.ACT }}
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Cargo Package Version
        if: ${{ ! env.ACT }}
        run: |
          echo "CARGO_PKG_VERSION=$(grep '^version' Cargo.toml | sed 's/version = "\(.*\)"/\1/')" >> $GITHUB_ENV
      # Download release assets from artifacts
      - name: Download release assets
        if: ${{ ! env.ACT }}
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/target
      # Upload release assets
      - name: Upload release assets
        if: ${{ ! env.ACT }}
        run: |
          gh release upload "v${{ env.CARGO_PKG_VERSION }}" ${{ github.workspace }}/target/rmx-${{ env.CARGO_PKG_VERSION }}-${{ matrix.target }}/rmx-${{ env.CARGO_PKG_VERSION }}-${{ matrix.target }} --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

