name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: read
  deployments: read
  issues: read
  pull-requests: read
  id-token: write

jobs:
  prep-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prep.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup Nu Tools
        uses: ck3mp3r/actions/nu-tools@main

      - name: Prepare release
        id: prep
        shell: nu {0}
        run: |
          use nu-tools *
          setup-git-user

          let current_version = (open Cargo.toml).package.version
          let latest_tag = (get-latest-tag)
          let version = (semver-calculate $latest_tag $current_version | create-release-branch)
          update-cargo-version $version | commit-files $"Prepare release ($version)"
          $"version=($version)" | save --append $env.GITHUB_OUTPUT

  build:
    needs: prep-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            nix_system: x86_64-linux
          - os: macos-14
            nix_system: aarch64-darwin
          - os: ubuntu-latest
            nix_system: aarch64-linux
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release/${{ needs.prep-release.outputs.version }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20

      - name: Build archive for ${{ matrix.nix_system }}
        run: nix build --system ${{ matrix.nix_system }} .#archive --print-build-logs

      - name: Copy build outputs for uniqueness
        run: |
          # Single-artifact approach: rustnix creates system-named files
          cp result/laio-${{ matrix.nix_system }}.tgz ${{ github.workspace }}/laio-${{ needs.prep-release.outputs.version }}-${{ matrix.nix_system }}.tgz
          cp result/laio-${{ matrix.nix_system }}.sha256 ${{ github.workspace }}/laio-${{ needs.prep-release.outputs.version }}-${{ matrix.nix_system }}.sha256
          cp result/laio-${{ matrix.nix_system }}-nix.sha256 ${{ github.workspace }}/laio-${{ needs.prep-release.outputs.version }}-${{ matrix.nix_system }}-nix.sha256

      - name: Upload build outputs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: laio-assets-${{ matrix.nix_system }}
          path: |
            ${{ github.workspace }}/laio-${{ needs.prep-release.outputs.version }}-${{ matrix.nix_system }}.tgz
            ${{ github.workspace }}/laio-${{ needs.prep-release.outputs.version }}-${{ matrix.nix_system }}.sha256
            ${{ github.workspace }}/laio-${{ needs.prep-release.outputs.version }}-${{ matrix.nix_system }}-nix.sha256

  finalize-release:
    needs:
      - prep-release
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT }}

      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release/${{ needs.prep-release.outputs.version }}
          fetch-depth: 0
          token: ${{ steps.token.outputs.token }}

      - name: Setup Nu Tools
        uses: ck3mp3r/actions/nu-tools@main

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Finalize release
        shell: nu {0}
        run: |
          use nu-tools *
          setup-git-user

          let version = "${{ needs.prep-release.outputs.version }}"

          # Generate platform data and commit
          generate-platform-data-for $version "laio" "./artifacts" | commit-files $"Add platform data for release ($version)"

          # Update Homebrew formula with new version and hashes
          let aarch64_darwin_hash = (open $"./artifacts/laio-assets-aarch64-darwin/laio-($version)-aarch64-darwin.sha256" | str trim)
          let aarch64_linux_hash = (open $"./artifacts/laio-assets-aarch64-linux/laio-($version)-aarch64-linux.sha256" | str trim)
          let x86_64_linux_hash = (open $"./artifacts/laio-assets-x86_64-linux/laio-($version)-x86_64-linux.sha256" | str trim)
          
          let formula_content = (open Formula/laio.rb)
          let updated_formula = (
            $formula_content
            | str replace -r 'version "[^"]*"' $'version "($version)"'
            | str replace -r 'v[0-9]+\.[0-9]+\.[0-9]+' $'v($version)' --all
            | str replace -r 'laio-[0-9]+\.[0-9]+\.[0-9]+-aarch64-darwin\.tgz' $'laio-($version)-aarch64-darwin.tgz'
            | str replace -r 'laio-[0-9]+\.[0-9]+\.[0-9]+-aarch64-linux\.tgz' $'laio-($version)-aarch64-linux.tgz'  
            | str replace -r 'laio-[0-9]+\.[0-9]+\.[0-9]+-x86_64-linux\.tgz' $'laio-($version)-x86_64-linux.tgz'
            | str replace -r 'sha256 "33643d682abd23761c84b6c3bc9ab4a1f026a401c68c6f3db1a812b74750d977"' $'sha256 "($aarch64_darwin_hash)"'
            | str replace -r 'sha256 "50706fc5a04fb8ff85c8bc0d2f9c0d21d6233a8b9a051a01a61e25b6708313d6"' $'sha256 "($aarch64_linux_hash)"'
            | str replace -r 'sha256 "b7302dd5c42250474923230771239276471d47888516e40e1320650befcb69a9"' $'sha256 "($x86_64_linux_hash)"'
          )
          $updated_formula | save Formula/laio.rb
          git add Formula/laio.rb
          git commit -m $"Update Homebrew formula to ($version)"

          # Create release and upload artifacts using gh CLI
          create-github-release $version
          glob "./artifacts/**/*.*" | upload-release-artifacts $version

          # Merge and cleanup
          merge-and-cleanup $version
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}

