---
name: Test 

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - Cargo.*
      - flake.*
      - src/**
      - .github/workflows/**

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      # - uses: DeterminateSystems/flake-checker-action@main

      - run: nix develop --command cargo test
