---
name: Test 

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - Cargo.*
      - flake.*
      - src/**
      - .github/workflows/**

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix flake check
      - run: nix develop --command cargo test
