---
name: test 

on:
  push:
    paths:
      - src/**
      - .github/workflows/main.yaml
      - .github/workflows/release.yaml
      - .github/workflows/test.yaml

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Test Binary
        run: |
          cargo test
