---
name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - Cargo.*
      - flake.*
      - src/**
      - .github/workflows/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Detect Nix system
        id: detect_system
        run: |
          if [[ "${{ runner.os }}" == "Linux" && "${{ runner.arch }}" == "X64" ]]; then
            echo "nix_system=x86_64-linux" >> $GITHUB_OUTPUT
          elif [[ "${{ runner.os }}" == "Linux" && "${{ runner.arch }}" == "ARM64" ]]; then
            echo "nix_system=aarch64-linux" >> $GITHUB_OUTPUT
          fi

      - name: Download Nix installer
        if: ${{ env.ACT }}
        run: |
          curl -L https://cf.install.determinate.systems/nix-installer/stable/${{ steps.detect_system.outputs.nix_system }}  -o /tmp/nix-installer-${{ steps.detect_system.outputs.nix_system }}
          chmod +x /tmp/nix-installer-${{ steps.detect_system.outputs.nix_system }}

      - uses: DeterminateSystems/nix-installer-action@main
        if: ${{ !env.ACT }}

      - uses: DeterminateSystems/nix-installer-action@main
        if: ${{ env.ACT }}
        with:
          local-root: /tmp

      - uses: DeterminateSystems/flake-checker-action@main

      - run: nix build --print-build-logs .#laio-${{ steps.detect_system.outputs.nix_system }}
