---
name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - Cargo.*
      - flake.*
      - src/**
      - .github/workflows/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - run: nix build .#laio-x86_64-linux
